### ISSUE TITLE
IntranetUserJS: Move item list to bottom on modify

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/koha-plugin-intranetjs-move-item-list-to-bottom#1]
Testaus/käyttöönotto:

Poista intranetUserJS-asetuksesta rimpsu /*Siirretään item-listaus sivun loppuun itemin muokkaussivulla (Tritonia, päivitetty 2020)*/
(saattaa olla myös eri otsikolla)

Aktivoi plugin
Tarkista, että nidelistaus on siirtynyt sivun alalaitaan niteen muokkauksessa.

**Comment by lmstrand** [comment]
Seuranta kimpoista, joissa otettu käyttöön:

- [ ] Lappi
- [ ] OUTI
- [ ] Siili
- [ ] Vaara
- [ ] Lumme
- [ ] Kyyti
- [ ] Helle
- [ ] Kirkes
- [ ] Lastu
- [ ] Vaski

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä. Ei toimi järkevästi, sillä kun menee niteen muokkausnäytölle, kursori menee sivun alareunaan niteiden osioon, vaikka oletettavasti tarkoitus on mennä sivun alkuun?

**Comment by pknuuti** [comment]
Nextillä toimii järkevämmin tällä hetkellä ilman tuota plugaria.

**Comment by lmstrand** [comment]
Lisäsin pluginiin skrollauksen tuohon editointikaavakkeeseen.

**Comment by atarnus** [comment]
Outissa tämä rimpsu löytyi tosiaan eri nimellä:
_/* Niteen muokkauksessa nidelistan siirto niteen muokkauksen alapuolelle */_

Elementti, jota muutetaan:
 #cataloguing_additem_itemlist

Testaillaan vielä erikseen halutaanko plugari käyttöön vai ei.

**Comment by Rvallim0** [comment]
Vaskin nextillä plugari vaikuttaa muuten toimivan, mutta aiheuttaa sen että muokkausnäytöllä hieman alas scrollatessa sivun yläreunaan ilmestyy items-taulukon sarakeotsikkorivi. Tätä ei aikaisemmin tapahtunut.
![kuva](https://github.com/user-attachments/assets/37563915-1c55-4a7a-af25-99d78bd62f34)

**Comment by lmstrand** [comment]
Sain sittenkin poistettua tuon dynaamisen otsikkorivin ilmestymisen. Nyt se ei enää häiritse.

**Comment by lmstrand** [comment]
Koska tämä javascript-rimpsu toimii oikein intranetUserJS-asetuksen kautta sarakeotsikkorivien kanssa ja plugin rikkoo tuon toiminnan, niin poistetaan tämä liitännäinen. Tätä toimintoa voi siis ylläpitää edelleen intranetUserJS-asetuksessa kuten ennenkin kimpan niin halutessa.

**Comment by lmstrand** [comment]
Kiitos testailuista. Jätän tämän repon ja tiketin vielä tänne näkyville toistaiseksi.
